# Have these settings apply to servers in my organization
# hostname hamilton*

# Setup zsh to read its files from .config/zsh
env ZDOTDIR=$HOME/.config/zsh
copy --dest .config/zsh/.zshrc .zshrc

copy --glob $HOME/.config/nvim/*
