#!/usr/bin/env sh
# for this to work you must configure sudo such that
# it will be able to run the command without password

yabai -m signal --add event=dock_did_restart action="sudo yabai --load-sa"
yabai -m signal --add event=display_changed action="yabai -m config focus_follows_mouse autoraise"
yabai -m signal --add event=mission_control_exit action="yabai -m config focus_follows_mouse autoraise"
yabai -m signal --add event=display_changed action="yabai -m config focus_follows_mouse autoraise"
yabai -m signal --add event=mission_control_exit action="yabai -m config focus_follows_mouse autoraise"
sudo yabai --load-sa

yabai -m rule --add app="Notes" sub-layer=above manage=off
yabai -m rule --add app="Finder" manage=off
yabai -m rule --add app="Finder" title="(Co(py|nnect)|Move|Info|Pref)" manage=off
yabai -m rule --add app="Preferences" app="^System Preferences$" manage=off
yabai -m rule --add app="System Settings$" manage=off
yabai -m rule --add app="^Activity Monitor$" manage=off
yabai -m rule --add app="Brave Browser" title="Bitwarden" manage=off
yabai -m rule --add app="Digital Colour Meter" sticky=on

yabai -m config                                 \
    layout                       bsp            \
    external_bar                 off:0:0        \
    menubar_opacity              1.0            \
    mouse_follows_focus          off            \
    focus_follows_mouse          autofocus      \
    display_arrangement_order    default        \
    window_origin_display        default        \
    window_placement             second_child   \
    window_insertion_point       focused        \
    window_zoom_persist          on             \
    window_shadow                on             \
    window_animation_duration    0.22           \
    window_animation_easing      ease_out_circ  \
    window_opacity               on             \
    window_opacity_duration      0.0            \
    active_window_opacity        1.0            \
    normal_window_opacity        0.78           \
    insert_feedback_color        0xffb0c4de     \
    split_ratio                  0.50           \
    split_type                   auto           \
    auto_balance                 off            \
    top_padding                  8              \
    bottom_padding               8              \
    left_padding                 8              \
    right_padding                8              \
    window_gap                   6              \
    mouse_modifier               cmd            \
    mouse_action1                move           \
    mouse_action2                resize         \
    mouse_drop_action            swap


