#!/usr/bin/env sh

# for this to work you must configure sudo such that
# it will be able to run the command without password

yabai -m signal --add event=dock_did_restart action="sudo yabai --load-sa"
sudo yabai --load-sa

yabai -m rule --add app="^Notes" manage=off sub-layer=below
yabai -m rule --add app="^Finder" manage=off sub-layer=below

yabai -m rule --add app="^Digital Colour Meter$" sticky=on



# global settings
yabai -m config                                 \
    layout 		                   bsp            \
    external_bar                 off:0:0       \
    menubar_opacity              1.0            \
    mouse_follows_focus          off            \
    focus_follows_mouse          on             \
    display_arrangement_order    default        \
    window_origin_display        default        \
    window_placement             second_child   \
    window_insertion_point       focused        \
    window_zoom_persist          on             \
    window_shadow                on             \
    window_animation_duration    0.0            \
    window_animation_easing      ease_out_circ  \
    window_opacity               on             \
    window_opacity_duration      0.0            \
    active_window_opacity        1.0            \
    normal_window_opacity        0.88           \
    insert_feedback_color        0xffd75f5f     \
    split_ratio                  0.50           \
    split_type                   auto           \
    auto_balance                 off            \
    top_padding                  8             \
    bottom_padding               8             \
    left_padding                 8             \
    right_padding                8             \
    window_gap                   6             \
    mouse_modifier               cmd             \
    mouse_action1                move           \
    mouse_action2                resize         \
    mouse_drop_action            swap

  for evt in window_created window_destroyed window_moved \
             window_minimized window_deminimized \
             space_changed display_changed; do
    yabai -m signal --add event="$evt" action="~/.config/yabai/yabai-utils.sh"
  done

echo "yabai configuration loaded.."

